In [2]:
from deepforest import main
from deepforest import get_data
import cv2
import os
import matplotlib.pyplot as plt

In [3]:
#img_path = 'C:\bin\python\jupyter-notebook\remote-sensing-deepforest\images\2-zomba.png'
#img = cv2.imread(img_path)
# type(main)
#m = main.deepforest()
#m.use_release()
#print("Current device is {}".format(m.device))
#m.to("cuda")
#print("Current device is {}".format(m.device))
#my_model = deepforest.deepforest()
#my_model.use_release()

In [9]:
model = main.deepforest()
model.use_release()

#img = model.predict_image(path="/Users/benweinstein/Documents/NeonTreeEvaluation/evaluation/RGB/TEAK_049_2019.tif",return_plot=True)

#predict_image returns plot in BlueGreenRed (opencv style), but matplotlib likes RedGreenBlue, switch the channel order.
#plt.imshow(img[:,:,::-1])

Reading config file: c:\bin\dev\remote-sensing-deepforest\env\Lib\site-packages\deepforest\data\deepforest_config.yml


GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


No validation file provided. Turning off validation loop
Model from DeepForest release https://github.com/weecology/DeepForest/releases/tag/1.0.0 was already downloaded. Loading model from file.
Loading pre-built model: https://github.com/weecology/DeepForest/releases/tag/1.0.0
None


In [11]:
img_path = "C:\\bin\dev\\remote-sensing-deepforest\images\\2-zomba.png"
img = cv2.imread(img_path)
print(img)

[[[112 109 116]
  [106 103 111]
  [ 97  93 104]
  ...
  [ 64  60  68]
  [ 48  42  49]
  [ 62  56  61]]

 [[116 113 121]
  [105 102 110]
  [ 91  88  99]
  ...
  [ 59  56  62]
  [ 58  53  59]
  [ 62  56  61]]

 [[ 90  87  96]
  [ 62  59  70]
  [ 49  45  61]
  ...
  [ 63  59  67]
  [ 67  61  68]
  [ 62  55  62]]

 ...

 [[ 51  55  45]
  [ 51  56  48]
  [ 46  52  47]
  ...
  [ 59  60  61]
  [ 80  83  85]
  [108 112 116]]

 [[ 53  57  45]
  [ 51  56  45]
  [ 37  43  35]
  ...
  [ 54  56  53]
  [ 97 101  99]
  [118 122 123]]

 [[ 45  50  35]
  [ 53  59  46]
  [ 38  45  35]
  ...
  [ 51  54  45]
  [ 92  96  90]
  [124 130 126]]]


In [12]:
print(type(img))
if type(img) != None and img.size != 0:
    cv2.imshow('input', img)
    cv2.waitKey(0)

<class 'numpy.ndarray'>


In [13]:
box_info = model.predict_image(img, return_plot=False)
box_info

c:\bin\dev\remote-sensing-deepforest\env\Lib\site-packages\deepforest\main.py:283: UserWarning: Image type is uint8, transforming to float32. This assumes that the range of pixel values is 0-255, as opposed to 0-1.To suppress this warning, transform image (image.astype('float32')
  warnings.warn(f"Image type is {image.dtype}, transforming to float32. "


xmin   ymin   xmax   ymax label     score
0   513.0  358.0  539.0  385.0  Tree  0.521271
1   484.0  325.0  507.0  348.0  Tree  0.452705
2    93.0  400.0  127.0  430.0  Tree  0.385173
3   568.0  259.0  607.0  298.0  Tree  0.328978
4   549.0  153.0  586.0  188.0  Tree  0.307558
5   114.0  441.0  148.0  471.0  Tree  0.238549
6   136.0  370.0  156.0  390.0  Tree  0.236067
7   601.0  321.0  629.0  346.0  Tree  0.232173
8   513.0  121.0  549.0  156.0  Tree  0.228671
9   481.0  385.0  506.0  409.0  Tree  0.215493
10  295.0    0.0  331.0    9.0  Tree  0.197337
11  552.0  298.0  573.0  320.0  Tree  0.180180
12    2.0  469.0   29.0  502.0  Tree  0.177848
13  406.0  112.0  429.0  134.0  Tree  0.175202
14   75.0  206.0  100.0  231.0  Tree  0.161605
15  263.0  394.0  288.0  421.0  Tree  0.160993
16  458.0  469.0  479.0  491.0  Tree  0.155218
17    7.0  250.0   40.0  281.0  Tree  0.154078
18  419.0  383.0  444.0  409.0  Tree  0.150958
19   95.0  238.0  128.0  273.0  Tree  0.147884
20  378.0  489.0  409.0  518.0  Tree  0.143528
21  444.0  348.0  469.0  373.0  Tree  0.142746
22   40.0  234.0   62.0  256.0  Tree  0.140481
23  494.0   67.0  520.0   93.0  Tree  0.140442
24  468.0  280.0  489.0  301.0  Tree  0.129133
25  464.0  138.0  486.0  159.0  Tree  0.122700
26  180.0  384.0  206.0  408.0  Tree  0.121023
27    0.0  500.0   10.0  520.0  Tree  0.114127

In [14]:
for n in range(len(box_info)):
    x = (box_info.xmin[n]+box_info.xmax[n]) / 2
    y = (box_info.ymin[n]+box_info.ymax[n]) / 2
    cv2.circle(img, (int(x), int(y)), 25, (0,255,0), 2)

cv2.putText(img, f'TOTAL TREES: {str(len(box_info))}', (3,14), cv2.FONT_HERSHEY_SIMPLEX, .5, (255,255,255))

array([[[112, 109, 116],
        [106, 103, 111],
        [ 97,  93, 104],
        ...,
        [ 64,  60,  68],
        [ 48,  42,  49],
        [ 62,  56,  61]],

       [[116, 113, 121],
        [105, 102, 110],
        [ 91,  88,  99],
        ...,
        [ 59,  56,  62],
        [ 58,  53,  59],
        [ 62,  56,  61]],

       [[ 90,  87,  96],
        [ 62,  59,  70],
        [ 49,  45,  61],
        ...,
        [ 63,  59,  67],
        [ 67,  61,  68],
        [ 62,  55,  62]],

       ...,

       [[ 51,  55,  45],
        [ 51,  56,  48],
        [ 46,  52,  47],
        ...,
        [ 59,  60,  61],
        [ 80,  83,  85],
        [108, 112, 116]],

       [[ 53,  57,  45],
        [ 51,  56,  45],
        [ 37,  43,  35],
        ...,
        [ 54,  56,  53],
        [ 97, 101,  99],
        [118, 122, 123]],

       [[ 45,  50,  35],
        [ 53,  59,  46],
        [ 38,  45,  35],
        ...,
        [ 51,  54,  45],
        [ 92,  96,  90],
        [124, 130, 126]]

In [15]:
cv2.imshow('output', img)
cv2.waitKey(0)

-1